spring:
  application:
    name: Printer-Queue-Telegram-Bot
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

bot:
  name: "PrinterQueueBot"
  token: ${BOT_TOKEN}
  stlPath: ${STL_DIR_PATH}

whitelist:
  admins:
    - ${ADMIN_1}
    - ${ADMIN_2}
    - ${ADMIN_3}
    - ${ADMIN_4}

server:
  port: 8080
