spring:
  application:
    name: Printer-Queue-Telegram-Bot
  datasource:
    url: jdbc:mysql://db:3306/printer_queue_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  liquibase:
    change-log: classpath:liquibase/changelog-master.yaml

bot:
  name: "PrinterQueueBot"
  token: 7865570662:AAHf6lRUrFjycZGFps9PBOHzcGFf_4I51L8
  stlPath: uploads

whitelist:
  admins:
    - llewelll

server:
  port: 8080
