package org.printerbot.printerqueuetelegrambot.bot.constants;

public enum BotState {
	NONE,

	WAITING_PRINTER_BRAND,

	WAITING_PRINTER_MODEL,

	WAITING_PRINTER_FEATURES,

	WAITING_PRINTER_AVAILABILITY,

	WAITING_PRINTER_MAX_PLASTIC_CAPACITY,

	WAITING_PRINTER_SUPPORTED_PLASTIC,

	WAITING_PLASTIC_BRAND,

	WAITING_PLASTIC_TYPE,

	WAITING_PLASTIC_COLOR,

	WAITING_PLASTIC_AVAILABILITY,

	WAITING_PLASTIC_DESCRIPTION

}
