package org.printerbot.printerqueuetelegrambot.bot.constants;

public enum BotState {
	NONE,

	WAITING_PRINTER_BRAND,

	WAITING_PRINTER_MODEL,

	WAITING_PRINTER_FEATURES,

	WAITING_PRINTER_AVAILABILITY,

	WAITING_PRINTER_MAX_PLASTIC_CAPACITY,

	WAITING_PRINTER_SUPPORTED_PLASTIC,

	WAITING_PLASTIC_BRAND,

	WAITING_PLASTIC_TYPE,

	WAITING_PLASTIC_COLOR,

	WAITING_PLASTIC_AVAILABILITY,

	WAITING_PLASTIC_DESCRIPTION,

	WAITING_PRINTER_BRAND_MOD,

	WAITING_PRINTER_MODEL_MOD,

	WAITING_PRINTER_FEATURES_MOD,

	WAITING_PRINTER_MAX_PLASTIC_CAPACITY_MOD,

	WAITING_PRINTER_ADD_SUPPORTED_PLASTIC_MOD,

	WAITING_PRINTER_REMOVE_SUPPORTED_PLASTIC_MOD,

	WAITING_PLASTIC_BRAND_MOD,

	WAITING_PLASTIC_TYPE_MOD,

	WAITING_PLASTIC_COLOR_MOD,

	WAITING_PLASTIC_AVAILABILITY_MOD,

	WAITING_PLASTIC_DESCRIPTION_MOD,

	SENDING_DOCUMENT

}
